/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package repositoio1;

import javax.swing.JOptionPane;

/**
 *
 * @author user
 */
public class pricipal extends javax.swing.JFrame {

    /**
     * Creates new form pricipal
     */
    public pricipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cmdcalcular = new javax.swing.JButton();
        cmdborrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtvalor1 = new javax.swing.JTextField();
        txtvalor2 = new javax.swing.JTextField();
        txtvalor3 = new javax.swing.JTextField();
        txtresultado1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        txtresultado2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        txtresultado3 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 420, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 308, -1, -1));

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setText("OBTENGA SU PORCENTAJE");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, 180, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel3.setText("% PERSONA 1:");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("& PERSONA 2:");
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 80, 30));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("% PERSONA 3: ");
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, 90, 30));

        cmdcalcular.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdcalcular.setText("OBTENER PORCENTAJE");
        cmdcalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdcalcularActionPerformed(evt);
            }
        });
        jPanel4.add(cmdcalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 370, -1, -1));

        cmdborrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        cmdborrar.setText("BORRAR");
        cmdborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmdborrarActionPerformed(evt);
            }
        });
        jPanel4.add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 370, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel6.setText("RESULTADO P1 :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, 110, 20));

        txtvalor1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtvalor1ActionPerformed(evt);
            }
        });
        txtvalor1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalor1KeyTyped(evt);
            }
        });
        jPanel4.add(txtvalor1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 120, 30));

        txtvalor2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalor2KeyTyped(evt);
            }
        });
        jPanel4.add(txtvalor2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 120, 30));

        txtvalor3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtvalor3KeyTyped(evt);
            }
        });
        jPanel4.add(txtvalor3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 120, 30));

        txtresultado1.setEditable(false);
        txtresultado1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultado1ActionPerformed(evt);
            }
        });
        jPanel4.add(txtresultado1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 120, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel7.setText("RESULTADO P2 :");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 100, 30));

        txtresultado2.setEditable(false);
        jPanel4.add(txtresultado2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 260, 120, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel8.setText("RESULTADO P3 :");
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, 100, 30));

        txtresultado3.setEditable(false);
        txtresultado3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtresultado3ActionPerformed(evt);
            }
        });
        jPanel4.add(txtresultado3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 310, 120, 30));

        getContentPane().add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 520, 410));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cmdcalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdcalcularActionPerformed
        String v1, v2, v3, res;
        double valor1 = 0, valor2 = 0, valor3 = 0, pv1, pv2, pv3, vlt;

        txtresultado1.setText("");
        txtresultado2.setText("");
        txtresultado3.setText("");

        if (txtvalor1.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el valor 1", "Error", JOptionPane.ERROR_MESSAGE);
            txtvalor1.requestFocusInWindow();
        } else if (txtvalor2.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el valor 2", "Error", JOptionPane.ERROR_MESSAGE);
            txtvalor2.requestFocusInWindow();
        } else if (txtvalor3.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "Digite el valor 3", "Error", JOptionPane.ERROR_MESSAGE);
            txtvalor3.requestFocusInWindow();
        } else {

            valor1 = Double.parseDouble(txtvalor1.getText());
            valor2 = Double.parseDouble(txtvalor2.getText());
            valor3 = Double.parseDouble(txtvalor3.getText());

            if (valor1 == 0) {
                JOptionPane.showMessageDialog(this, "No se permite el numero 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtvalor1.requestFocusInWindow();
                txtvalor1.selectAll();
            } else if (valor2 == 0) {
                JOptionPane.showMessageDialog(this, "No se permite el numero 0", "Error", JOptionPane.ERROR_MESSAGE);
                txtvalor2.requestFocusInWindow();
                txtvalor2.selectAll();
            } else {

                vlt = valor1 + valor2 + valor3;

                pv1 = (valor1 / vlt) * 100;

                pv2 = (valor2 / vlt) * 100;

                pv3 = (valor3 / vlt) * 100;

                res = String.valueOf(vlt);
                res = String.valueOf(pv1);
                res = String.valueOf(pv2);
                res = String.valueOf(pv3);

                txtresultado1.setText(String.valueOf(pv1) + "%");
                txtresultado2.setText(String.valueOf(pv2) + "%");
                txtresultado3.setText(String.valueOf(pv3) + "%");

            }

        }


    }//GEN-LAST:event_cmdcalcularActionPerformed

    private void txtresultado1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultado1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultado1ActionPerformed

    private void cmdborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmdborrarActionPerformed
        txtvalor1.setText("");
        txtvalor2.setText("");
        txtvalor3.setText("");
        txtresultado1.setText("");
        txtresultado2.setText("");
        txtresultado3.setText("");

        txtvalor1.requestFocusInWindow();

    }//GEN-LAST:event_cmdborrarActionPerformed

    private void txtresultado3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtresultado3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtresultado3ActionPerformed

    private void txtvalor1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalor1KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtvalor1KeyTyped

    private void txtvalor2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalor2KeyTyped
        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();;
            evt.consume();
        }
    }//GEN-LAST:event_txtvalor2KeyTyped

    private void txtvalor1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtvalor1ActionPerformed
    }//GEN-LAST:event_txtvalor1ActionPerformed

    private void txtvalor3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtvalor3KeyTyped

        char c = evt.getKeyChar();

        if (!Character.isDigit(c)) {
            getToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtvalor3KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pricipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pricipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdcalcular;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTextField txtresultado1;
    private javax.swing.JTextField txtresultado2;
    private javax.swing.JTextField txtresultado3;
    private javax.swing.JTextField txtvalor1;
    private javax.swing.JTextField txtvalor2;
    private javax.swing.JTextField txtvalor3;
    // End of variables declaration//GEN-END:variables
}
